carts/urls.py
from django.urls import path
# from carts.views import #cart_home#,#add_to_cart#, checkout_home
from . import views
app_name = 'carts'


urlpatterns = [
    # path('',cart_home,name ='home'),
    
    # path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    # path('checkout',checkout_home,name = 'checkout')
]

checkouts/urls.py
from django.urls import path
from .views import (
    CheckoutView,
    AddCouponView,
)

app_name = 'checkouts'

urlpatterns = [
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('add-coupon/', AddCouponView.as_view(), name='add_coupon'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'


urlpatterns = [
    # path('',cart_home,name ='home'),
    path('order-summary/',views.OrderSummaryView.as_view(), name='order_summary'),
    path('refund/',views.RequestRefundView.as_view(), name='request_refund'),

    # path('order-summary/<slug>/',views.OrderDetailView, name='order_summary'),
    # path('checkout',checkout_home,name = 'checkout')
]

products/urls.py
from django.conf.urls import url
from django.urls import path
from . import views



app_name = 'products'

urlpatterns = [
  path('create',views.ProductCreateView.as_view(),name = 'product'),
  path('list',views.ProductListView.as_view(),name = 'product_list'),
  path('detail/<str:slug>',views.ProductDetailView.as_view(),name = 'product_detail'),
  path('update/<str:slug>',views.ProductUpdateView.as_view(),name ='product_update'),
  path('delete/<str:slug>',views.ProductDeleteView.as_view(),name ='product_delete'),


  #add to cart
  path('add-to-cart/<slug>/', views.add_to_cart, name='add_to_cart'),
  path('remove_from_cart/<slug>/', views.remove_from_cart, name='remove_from_cart'),
  path('remove_single_item_from_cart/<slug>/', views.remove_single_item_from_cart, name='remove_single_item_from_cart'),
  

]

source/urls.py
from django.urls import include, path
from django.contrib import admin
from . import views,settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from django.views import generic

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomeView.as_view(),name = 'home'),  
    path('dashboard',views.DashboardView.as_view(),name='dashboard'),
    path('thank',views.ThanksView.as_view(),name='thank'),

    #Auth django stuff 
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),name ='password_reset'),
    path('passsword_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),name = 'password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),name = 'password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),name ='password_reset_complate'),
    path('logout/',auth_views.LogoutView.as_view(),name ='logout'),
    # Apps root 

    path('accounts/', include('accounts.urls',namespace = 'accounts')),
    path('profiles/', include('profiles.urls',namespace = 'profiles')),
    path('categories/', include('categories.urls',namespace = 'categories')),
    path('shoprequests/', include('shoprequests.urls',namespace = 'shoprequests')),
    path('shops/', include('shops.urls',namespace = 'shops')),
    path('search/', include('search.urls',namespace = 'search')),
    path('products/', include('products.urls',namespace = 'products')),
    path('carts/', include('carts.urls',namespace = 'carts')),
    path('orders/', include('orders.urls',namespace = 'orders')),
    path('checkouts/', include('checkouts.urls',namespace = 'checkouts')),
    path('payments/', include('payments.urls',namespace = 'payments')),


]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from django.contrib import auth
from carts.models import Cart
from payments.models import Payment
from checkouts.models import Address,Coupon

# Create your models here.
class Order(models.Model):

    user = models.ForeignKey(auth.models.User, on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    products = models.ManyToManyField(Cart)
    create_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    subtotal = models.DecimalField(default =30.00, max_digits=100, decimal_places=2)
    # total = models.DecimalField(default =0.00, max_digits=100, decimal_places=2)
 
    shipping_address = models.ForeignKey(
        Address, related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        Address, related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        Payment, on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        Coupon, on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


    def get_total(self):
        total = 0
        for order_item in self.products.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount   
        return total


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"

orders/forms.py
from django import forms 



class RefundForm(forms.Form):
    ref_code = forms.CharField()
    message = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 4
    }))
    email = forms.EmailField()

orders/views.py
from django.shortcuts import render,redirect
from django.views.generic import DetailView,TemplateView,View
from .models import Order,Refund
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from .forms import RefundForm
# Create your views here.


class OrderSummaryView(View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'order': order
            }
            return render(self.request, 'orders/home.html', context)
        except ObjectDoesNotExist:
            messages.warning(self.request, "You do not have an active order")
            return redirect("/")


class RequestRefundView(View):
    def get(self, *args, **kwargs):
        form = RefundForm()
        context = {
            'form': form
        }
        return render(self.request, "orders/request_refund.html", context)

    def post(self, *args, **kwargs):
        form = RefundForm(self.request.POST)
        if form.is_valid():
            ref_code = form.cleaned_data.get('ref_code')
            message = form.cleaned_data.get('message')
            email = form.cleaned_data.get('email')
            # edit the order
            try:
                order = Order.objects.get(ref_code=ref_code)
                order.refund_requested = True
                order.save()

                # store the refund
                refund = Refund()
                refund.order = order
                refund.reason = message
                refund.email = email
                refund.save()

                messages.info(self.request, "Your request was received.")
                return redirect("orders:request_refund")

            except ObjectDoesNotExist:
                messages.info(self.request, "This order does not exist.")
                return redirect("orders:request_refund")

orders/templates/orders/home.html
{% extends 'base.html' %}
{% block content %}
<h1>Order Summary </h1>

{% if order.products.exists %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Product Name</th>
      <th scope="col">quantity</th>
      <th scope="col">single piece price</th>
      <th scope="col">total piece Price</th>
      <th>discount</th>
      <th scope="col">Saved money</th>
      <th scope="col">Final ammount</th>
    </tr>
  </thead>
  <tbody>
  {% for cart in order.products.all %}
    <tr>
      <th scope="row">{{ forloop.counter}}</th>
      <td><a href="{{cart.product.get_absolute_url}}">{{ cart.product.title }}</a>
      {% comment %} {% include 'products/snippets/update_order.html' with product=product order=order %}{% endcomment %}
      </td>
      <td scope="col"> <a href={% url 'products:remove_single_item_from_cart' slug=cart.product.slug %}><i class="fa fa-minus mr-2" aria-hidden="true"></i></a>
      {{cart.quantity}}<a href={% url 'products:add_to_cart' slug=cart.product.slug %}><i class="fa fa-plus ml-2" aria-hidden="true"></i></a>
      </td>
     

      <td>{{ cart.product.price }}</td>
      <td>${{ cart.get_total_item_price}}</td>
      {% if cart.product.discount_price %}
      <td>${{ cart.get_total_discount_item_price}}</td>
      <td>${{ cart.get_final_price}}</td>
      <td>${{ cart.get_amount_saved}}</td>
      {% else %}
      <td>$0.00</td>
      <td>$0.00</td>
      <td>${{ cart.get_final_price}}</td>
      {% endif %}
       <td>${{ cart.get_final_price}}</td>
      <th scope="col"><a href={% url 'products:remove_from_cart' slug=cart.product.slug %}><i class="fa fa-trash" aria-hidden="true"></i>
</a></th>
    </tr>
    {% endfor %}
    <tr>
      <th colspan='6'></th>
      <td><b>Subtotal</b> {{ order.subtotal }}</td>
    </tr>
    {% if order.coupon %}
    <tr>
      <th colspan='6'></th>
      <td><b>coupon </b> -${{ order.coupon.amount}}</td>
    </tr>
    {% endif %}
    <tr>
      <th colspan='6'></th>
      <td><b>total</b> {{ order.get_total }}</td>
    </tr>
    <tr>
      <th colspan='2'></th>
      {% comment %} <td><a class='btn btn-success' href={%url 'orders:checkout'%}>Check out</a></td> {% endcomment %}
    </tr>
    {% if order.get_total %}
        <tr>
            <td colspan="8">
            <a class='btn btn-warning float-right ml-2' href='/checkouts/checkout/'>Proceed to checkout</a>
            <a class='btn btn-primary float-right' href='/products/list'>Continue shopping</a>
            </td>
        </tr>
    {% endif %}
  </tbody>
</table>
{% else %}
Cart is empty
{% endif %}
{% endblock content %}

orders/templates/orders/request_refund.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}