accounts/urls.py
from django.conf.urls import url
from django.urls import path
from accounts import views



app_name = 'accounts'

urlpatterns = [
    path('login/',views.CoustomLoginView.as_view(template_name='accounts/login.html'),name = 'login'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('activate/<uidb64>/<token>/',views.ActivateAccount.as_view(), name='activate'),
]

carts/urls.py
from django.urls import path
# from carts.views import #cart_home#,#add_to_cart#, checkout_home
from . import views
app_name = 'carts'


urlpatterns = [
    # path('',cart_home,name ='home'),
    
    # path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    # path('checkout',checkout_home,name = 'checkout')
]

source/urls.py
from django.urls import include, path
from django.contrib import admin
from . import views,settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from django.views import generic

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomeView.as_view(),name = 'home'),  
    path('dashboard',views.DashboardView.as_view(),name='dashboard'),
    path('thank',views.ThanksView.as_view(),name='thank'),

    #Auth django stuff 
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),name ='password_reset'),
    path('passsword_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),name = 'password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),name = 'password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),name ='password_reset_complate'),
    path('logout/',auth_views.LogoutView.as_view(),name ='logout'),
    # Apps root 

    path('accounts/', include('accounts.urls',namespace = 'accounts')),
    path('profiles/', include('profiles.urls',namespace = 'profiles')),
    path('categories/', include('categories.urls',namespace = 'categories')),
    path('shoprequests/', include('shoprequests.urls',namespace = 'shoprequests')),
    path('shops/', include('shops.urls',namespace = 'shops')),
    path('search/', include('search.urls',namespace = 'search')),
    path('products/', include('products.urls',namespace = 'products')),
    path('carts/', include('carts.urls',namespace = 'carts')),
    path('orders/', include('orders.urls',namespace = 'orders')),
    path('checkouts/', include('checkouts.urls',namespace = 'checkouts')),
    path('payments/', include('payments.urls',namespace = 'payments')),


]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.urls import reverse
from django.db import models
from django.contrib import auth
# from django.db.models.signals import post_save
# from django.dispatch import receiver

# Create your models here.

class User(auth.models.User,auth.models.PermissionsMixin):
    
    def __str__(self):
        return "@{}".format(self.username)

accounts/forms.py
from django.contrib.auth import get_user_model
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm


class CustomLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username','password']
      

    def __init__(self, *args, **kwargs):
        super(CustomLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = ('Enter your username')
        self.fields['username'].label = ''
        self.fields['password'].widget.attrs['placeholder'] = ('Password')
        self.fields['password'].label = ''

class UserCreateForm(UserCreationForm):

    class Meta:
        
        model = User
        fields = ["username","email","password1","password2"]
        
        widgets ={
            'email' : forms.TextInput(attrs={'class':'control-flow'}),
        
        }
        
    def clean_email(self):
        email = self.cleaned_data["email"]
        if User.objects.filter(email__iexact=email).exists():
            raise forms.ValidationError("Email is invalid")
        return email
        
    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = ('Enter your username')
        self.fields['username'].label = ''
        self.fields['email'].widget.attrs['placeholder'] = ('Enter your email')
        self.fields['email'].label = ''
        self.fields['password1'].widget.attrs['placeholder'] = ('Password')
        self.fields['password1'].label = ''
        self.fields['password2'].widget.attrs['placeholder'] = ('Confirm Password')
        self.fields['password2'].label = ''

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

accounts/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from .forms import UserCreateForm
from django.views.generic import CreateView,TemplateView,View
from . import forms
from source import settings
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
# email 
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from .tokens import account_activation_token

from django.contrib.auth import login
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.core.mail import send_mail
from django.contrib import messages

# Create your views here.

class SignUp(CreateView):
    form_class = UserCreateForm
    template_name = 'accounts/signup.html'
        
    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():

            user = form.save(commit=False)
            user.is_active = False # Deactivate account till it is confirmed
            user.save()

            current_site = get_current_site(request)
            subject = 'Activate Your Dotescrow Account'
            message = render_to_string('accounts/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)
            messages.success(request, 'Please verify you email to activate you account.')
            return redirect('accounts:signup')

        return render(request, self.template_name, {'form': form})



class CoustomLoginView(LoginView):
    authentication_form = forms.CustomLoginForm

 
class ActivateAccount(View):

    def get(self, request, uidb64, token, *args, **kwargs):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            print('user is active or not ',user.is_active)
            user.save()
            print('user is active or not ',user.is_active)
            messages.success(request, ('Your account have been confirmed.'))
            return redirect('accounts:login')
        else:
            messages.warning(request, ('The confirmation link was invalid, possibly because it has already been used.'))
            return redirect('accounts:signup')

accounts/templates/accounts/account_activation_email.html
{% autoescape off %}


<!DOCTYPE html>
<html>

<head>
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <style type="text/css">
        @media screen {
            @font-face {
                font-family: 'Lato';
                font-style: normal;
                font-weight: 400;
                src: local('Lato Regular'), local('Lato-Regular'), url(https://fonts.gstatic.com/s/lato/v11/qIIYRU-oROkIk8vfvxw6QvesZW2xOQ-xsNqO47m55DA.woff) format('woff');
            }

            @font-face {
                font-family: 'Lato';
                font-style: normal;
                font-weight: 700;
                src: local('Lato Bold'), local('Lato-Bold'), url(https://fonts.gstatic.com/s/lato/v11/qdgUG4U09HnJwhYI-uK18wLUuEpTyoUstqEm5AMlJo4.woff) format('woff');
            }

            @font-face {
                font-family: 'Lato';
                font-style: italic;
                font-weight: 400;
                src: local('Lato Italic'), local('Lato-Italic'), url(https://fonts.gstatic.com/s/lato/v11/RYyZNoeFgb0l7W3Vu1aSWOvvDin1pK8aKteLpeZ5c0A.woff) format('woff');
            }

            @font-face {
                font-family: 'Lato';
                font-style: italic;
                font-weight: 700;
                src: local('Lato Bold Italic'), local('Lato-BoldItalic'), url(https://fonts.gstatic.com/s/lato/v11/HkF_qI1x_noxlxhrhMQYELO3LdcAZYWl9Si6vvxL-qU.woff) format('woff');
            }
        }

        /* CLIENT-SPECIFIC STYLES */
        body,
        table,
        td,
        a {
            -webkit-text-size-adjust: 100%;
            -ms-text-size-adjust: 100%;
        }

        table,
        td {
            mso-table-lspace: 0pt;
            mso-table-rspace: 0pt;
        }

        img {
            -ms-interpolation-mode: bicubic;
        }

        /* RESET STYLES */
        img {
            border: 0;
            height: auto;
            line-height: 100%;
            outline: none;
            text-decoration: none;
        }

        table {
            border-collapse: collapse !important;
        }

        body {
            height: 100% !important;
            margin: 0 !important;
            padding: 0 !important;
            width: 100% !important;
        }

        /* iOS BLUE LINKS */
        a[x-apple-data-detectors] {
            color: inherit !important;
            text-decoration: none !important;
            font-size: inherit !important;
            font-family: inherit !important;
            font-weight: inherit !important;
            line-height: inherit !important;
        }

        /* MOBILE STYLES */
        @media screen and (max-width:600px) {
            h1 {
                font-size: 32px !important;
                line-height: 32px !important;
            }
        }

        /* ANDROID CENTER FIX */
        div[style*="margin: 16px 0;"] {
            margin: 0 !important;
        }
    </style>
</head>

<body style="background-color: #f4f4f4; margin: 0 !important; padding: 0 !important;">
    <!-- HIDDEN PREHEADER TEXT -->
    <div style="display: none; font-size: 1px; color: #fefefe; line-height: 1px; font-family: 'Lato', Helvetica, Arial, sans-serif; max-height: 0px; max-width: 0px; opacity: 0; overflow: hidden;"> We're thrilled to have you here! Get ready to dive into your new account. </div>
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <!-- LOGO -->
        <tr>
            <td bgcolor="green" align="center">
                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
                    <tr>
                        <td align="center" valign="top" style="padding: 40px 10px 40px 10px;"> </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td bgcolor="green" align="center" style="padding: 0px 10px 0px 10px;">
                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
                    <tr>
                        <td bgcolor="#ffffff" align="center" valign="top" style="padding: 40px 20px 20px 20px; border-radius: 4px 4px 0px 0px; color: #111111; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 48px; font-weight: 400; letter-spacing: 4px; line-height: 48px;">
                            <h1 style="font-size: 48px; font-weight: 400; margin: 2;">DOTEscrow</h1> <h4 style="font-size: 18px; font-weight: 400; margin: 2;">Hi {{ user.username }}</h4> <h1 style="font-size: 38px; font-weight: 400; margin: 2;">Welcome!</h1> <img src=" https://img.icons8.com/clouds/100/000000/handshake.png" width="125" height="120" style="display: block; border: 0px;" />
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td bgcolor="#f4f4f4" align="center" style="padding: 0px 10px 0px 10px;">
                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
                    <tr>
                        <td bgcolor="#ffffff" align="left" style="padding: 20px 30px 40px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;">
                            <p style="margin: 0;">We're excited to have you get started. First, you need to confirm your account. Just press the button below.</p>
                        </td>
                    </tr>
                    <tr>
                        <td bgcolor="#ffffff" align="left">
                            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td bgcolor="#ffffff" align="center" style="padding: 20px 30px 60px 30px;">
                                        <table border="0" cellspacing="0" cellpadding="0">
                                            <tr>
                                                <td align="center" style="border-radius: 3px;" bgcolor="green"><a href="http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}" target="_blank" style="font-size: 20px; font-family: Helvetica, Arial, sans-serif; color: #ffffff; text-decoration: none; color: #ffffff; text-decoration: none; padding: 15px 25px; border-radius: 2px; border: 1px solid green; display: inline-block;">Confirm Account</a></td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr> <!-- COPY -->
                    <tr>
                        <td bgcolor="#ffffff" align="left" style="padding: 0px 30px 0px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;">
                            <p style="margin: 0;">If that doesn't work, copy and paste the following link in your browser:</p>
                        </td>
                    </tr> <!-- COPY -->
                    <tr>
                        <td bgcolor="#ffffff" align="left" style="padding: 20px 30px 20px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;">
                            <p style="margin: 0;"><a href="http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}" target="_blank" style="color: green;">http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}</a></p>
                        </td>
                    </tr>
                    <tr>
                        <td bgcolor="#ffffff" align="left" style="padding: 0px 30px 20px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;">
                            <p style="margin: 0;">If you have any questions, just reply to this email—we're always happy to help out.</p>
                        </td>
                    </tr>
                    <tr>
                        <td bgcolor="#ffffff" align="left" style="padding: 0px 30px 40px 30px; border-radius: 0px 0px 4px 4px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;">
                            <p style="margin: 0;">Cheers,<br>FIT Team</p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        {% comment %} <!-- <tr>
            <td bgcolor="#f4f4f4" align="center" style="padding: 30px 10px 0px 10px;">
                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
                    <tr>
                        <td bgcolor="#FFECD1" align="center" style="padding: 30px 30px 30px 30px; border-radius: 4px 4px 4px 4px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;">
                            <h2 style="font-size: 20px; font-weight: 400; color: #111111; margin: 0;">Need more help?</h2>
                            <p style="margin: 0;"><a href="#" target="_blank" style="color: green;">We&rsquo;re here to help you out</a></p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr> --> {% endcomment %}
    </table>
</body>

</html>


{% endautoescape %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %}

{% block title %} Ecommerce | Log In {% endblock %}

{% block content %}
    <div class="container">
      <div class="container">
        <a href="{% url 'home' %}"><b>E</b>commerce</a>
      </div><!-- /.login-logo -->
      <div class="container">
        <p >Sign in to start your session</p>
        <form method="POST">{% csrf_token %}
          <div>
          {% bootstrap_field form.username %}
          </div>
          <div >
            {% bootstrap_field form.password %}
          </div>
          <div class="row container">
            <div class="col-xs-8">    
            <a href="{% url 'password_reset'%}">I forgot my password</a><br>
            <a href="{% url 'accounts:signup' %}" class="text-center">Register a new membership</a>         
            </div><!-- /.col -->
            <div class="col-xs-4">
              <button type="submit" >Sign In</button>
            </div><!-- /.col -->
          </div>
        </form>
{% endblock content %}

accounts/templates/accounts/password_reset.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %}

{% block content %}
  {% for message in messages %}
    {% if message %}
            <div class="alert alert-success container" style="textalign:center">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                    ×</button>
               <span class="glyphicon glyphicon-ok"></span> <strong>Reset password link is successfully sent</strong>
                <hr class="message-inner-separator">
                <p>{{message}}</p>
            </div>
    {% endif %}
    {% endfor %}

    <div class="container">
      <div class="container">
        <a href="{% url 'home'%}"><b>E</b>commerce</a>
      </div><!-- /.login-logo -->
      <div class="container">
        <p>Reset Password</p>
        <form method="POST">{% csrf_token %}
          <div class="">
          {% bootstrap_form form %}
            
          </div>
          <div class="row container">
            <div class="col-xs-4">
              <button type="submit" >Confirm</button>
            </div><!-- /.col -->
          </div>
        </form>
      </div><!-- /.login-box-body -->
    </div><!-- /.login-box -->

    <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script>
{% endblock content %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% include 'snippets/dashboard_header.html' %}
{% block content %}
<div class='container' style='margin-top:20px'>
<p class='alert alert-info'>Your password is successfully changed<p> 
<p><strong><a href="{% url 'accounts:login' %}">Log In</a></strong></p>
</div>

{% endblock  %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% include 'snippets/dashboard_header.html' %}
{% block content %}

<div class='container' style='margin-top:18px'>
{% if validlink %}
<h1>Reset Password</h1>

<form class='accounts' method = 'POST'>
{% csrf_token %}
{% bootstrap_form form %}
<input type='submit' class='btn btn-success' value = 'Confirm'> 
{% else %}

<p class='alert alert-info' >The password reset link was invalid, possibly because it has already been used.  Please request a new password reset.</p>
<p><strong><a href ="{% url 'password_reset' %}">password reset.</strong></a></p>
{% endif %}
</div>
{% endblock  %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% include 'snippets/dashboard_header.html' %}
{% block content %}
<div class='container' style='margin-top:20px'>
<p class='alert alert-info'>Check Your email to reset your password!<p> 
</div>
{% endblock  %}

accounts/templates/accounts/sent_confirm.html
{% load static %}
{% load bootstrap3 %}
{% block content %}
<div class='container' style='margin-top:20px'>
<p class='alert alert-info'>Your email is sent successfully. </p> 
</div>
{% endblock  %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %}

{% block content %}
   {% for message in messages %}
    {% if message %}
            <div class="alert alert-success container" style="textalign:center">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                    ×</button>
               <span class="glyphicon glyphicon-ok"></span> <strong>You're successfully registered</strong>
                <hr class="message-inner-separator">
                <p>{{message}}</p>
            </div>
    {% endif %}
    {% endfor %}
    <div class="register-box">
      <div class="container">
        <a href="{% url 'home' %}"><b>E</b>commerce</a>
      </div>

      <div class="container">
        <p >Register a new membership</p>
        <form method="POST">{% csrf_token %}
       
          <div class="form-group has-feedback">
          {% bootstrap_field form.username %}
        
          </div>
          <div class="form-group has-feedback">
          {% bootstrap_field form.email %}
    
          </div>
          <div class="form-group has-feedback">
            {% bootstrap_field form.password1 %}
      
          </div>
          <div class="form-group has-feedback">
            {% bootstrap_field form.password2 %}
        
          </div>
          <div class="row container">
            <div class="col-xs-8" style="margin-top:5px;">    
                       <a href="{% url 'accounts:login'%}" class="text-center">I already have a membership</a>         
            </div><!-- /.col -->
            <div class="col-xs-4">
              <button type="submit">Register</button>
            </div><!-- /.col -->
          </div>
        </form>        

       
      </div><!-- /.form-box -->
    </div><!-- /.register-box -->

   <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script>
{% endblock content %}