accounts/urls.py
from django.conf.urls import url
from django.urls import path
from accounts import views



app_name = 'accounts'

urlpatterns = [
    path('login/',views.CoustomLoginView.as_view(template_name='accounts/login.html'),name = 'login'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('activate/<uidb64>/<token>/',views.ActivateAccount.as_view(), name='activate'),
]

carts/urls.py
from django.urls import path
# from carts.views import #cart_home#,#add_to_cart#, checkout_home
from . import views
app_name = 'carts'


urlpatterns = [
    # path('',cart_home,name ='home'),
    
    # path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    # path('checkout',checkout_home,name = 'checkout')
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'


urlpatterns = [
    # path('',cart_home,name ='home'),
    path('order-summary/',views.OrderSummaryView.as_view(), name='order_summary'),
    path('refund/',views.RequestRefundView.as_view(), name='request_refund'),

    # path('order-summary/<slug>/',views.OrderDetailView, name='order_summary'),
    # path('checkout',checkout_home,name = 'checkout')
]

products/urls.py
from django.conf.urls import url
from django.urls import path
from . import views



app_name = 'products'

urlpatterns = [
  path('create',views.ProductCreateView.as_view(),name = 'product'),
  path('list',views.ProductListView.as_view(),name = 'product_list'),
  path('detail/<str:slug>',views.ProductDetailView.as_view(),name = 'product_detail'),
  path('update/<str:slug>',views.ProductUpdateView.as_view(),name ='product_update'),
  path('delete/<str:slug>',views.ProductDeleteView.as_view(),name ='product_delete'),


  #add to cart
  path('add-to-cart/<slug>/', views.add_to_cart, name='add_to_cart'),
  path('remove_from_cart/<slug>/', views.remove_from_cart, name='remove_from_cart'),
  path('remove_single_item_from_cart/<slug>/', views.remove_single_item_from_cart, name='remove_single_item_from_cart'),
  

]

search/urls.py
from django.urls import path
from search.views import SearchProductListView
from . import views

app_name ='search'

urlpatterns = [    
    path('',SearchProductListView.as_view(),name = 'query'),
]

source/urls.py
from django.urls import include, path
from django.contrib import admin
from . import views,settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from django.views import generic

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomeView.as_view(),name = 'home'),  
    path('dashboard',views.DashboardView.as_view(),name='dashboard'),
    path('thank',views.ThanksView.as_view(),name='thank'),

    #Auth django stuff 
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),name ='password_reset'),
    path('passsword_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),name = 'password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),name = 'password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),name ='password_reset_complate'),
    path('logout/',auth_views.LogoutView.as_view(),name ='logout'),
    # Apps root 

    path('accounts/', include('accounts.urls',namespace = 'accounts')),
    path('profiles/', include('profiles.urls',namespace = 'profiles')),
    path('categories/', include('categories.urls',namespace = 'categories')),
    path('shoprequests/', include('shoprequests.urls',namespace = 'shoprequests')),
    path('shops/', include('shops.urls',namespace = 'shops')),
    path('search/', include('search.urls',namespace = 'search')),
    path('products/', include('products.urls',namespace = 'products')),
    path('carts/', include('carts.urls',namespace = 'carts')),
    path('orders/', include('orders.urls',namespace = 'orders')),
    path('checkouts/', include('checkouts.urls',namespace = 'checkouts')),
    path('payments/', include('payments.urls',namespace = 'payments')),


]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/snippets/base_css.html
{% load static %}
<style type="text/css">
head{
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    font-weight: 380;
}

body{
    background-color: #f2f2f2;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    font-weight: 380;
}

:root {
    --main-background-color: #f2f2f2;
    --dard-background-color: #a2a2a2;
    --secondary-text-color: #808080;
    --light-primary-text-color:#0080ff;
}

</style>

templates/snippets/base_js.html
{% load static %}

templates/snippets/footer.html
<dir style='text-align:center;'>
  <p></b> Ecommerce developed by Ahmed Yasin </b></p>
</dir>

templates/snippets/header.html
{% load cart_template_tags %} 
<div>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="{% url 'home'%}">Ecommerce</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="{% url "home" %}">Home <span class="sr-only">(current)</span></a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url "logout" %}">logout</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "products:product_list" %}">Product List <span class="sr-only">(current)</span></a>
      </li>
      {% if user.is_staff %}
      <li class="nav-item">
        <a class="nav-link" href="{% url "products:product" %}">Sale Product<span class="sr-only">(current)</span></a>
      </li>
      {% endif %}
       <li class="nav-item">
        <a class="nav-link" href="{% url "profiles:profile" %}">Profile <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "shoprequests:shop_request" %}">Shop <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "categories:all_categories" %}">Categories <span class="sr-only">(current)</span></a>
      </li>
       <li class="nav-item">
      <a class="nav-link" href="{% url 'orders:order_summary' %}">{{request.user|cart_item_count}}<i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
      </li>
      
      {% if user.is_superuser %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
      </li>
        {% endif %}
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url "accounts:login" %}">login</a>
      </li>
      {% endif %}
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    {% if user.is_authenticated %}
    <form method='GET' action="{%url 'search:query'%}"> 
    <input type='text' placeholder = 'search' name='q' value={{request.GET.q}}>
    <button class='btn btn-success' type='submit' style='margin-left:px'>search</button>
    </form>
    {% endif %}
  </div>
</nav>
</div>